// This file contains the student data in an encoded format (Base64).
// This makes it harder for users to view or modify the data directly.
// To update this data, you must re-encode your original data.js file.
// See the README.md for instructions.

const encodedStudentData = "eyAKICAgIHJlZ051bWJlcjogIkFTUC8yMDIvMDAxIiwgCiAgICBuYW1lOiAiQS5CLlMuV2l0aGFuYWdlIiwgCiAgICBjZXJ0aWZpY2F0ZUlkOiAiZmFzMDAxIiAKICB9LAogIHsgCiAgICByZWdOdW1iZXI6ICJBU1AvMjAyLzAwMiIsIAogICAgbmFtZTogIkEuRy5OYW1hbCIsIAogICAgY2VydGlmaWNhdGVJZDogImZhczAwMiIgCiAgfSwKICB7IAogICAgcmVnTnVtYmVyOiAiQVNQLzIwMi8wMDMiLCAKICAgIG5hbWU6ICJBLkIuUy5XaXRoYW5hZ2UiLCAKICAgIGNlcnRpZmljYXRlSWQ6ICJmYXMwMDMiIAogIH0sCiAgLy8g4Lax4LeAIOC3geC3kuC3guC3iuKAjeC2uuC2uuC3jyDgtrjgt5ngtq3gtrHgtqcg4LaR4Laa4Lat4LeUIOC2muC2u+C2seC3iuC2sQogIHsgCiAgICByZWdOdW1iZXI6ICJBU1AvMjAyLzAwNCIsIAogICAgbmFtZTogIk5pbWFsIFBlcmVyYSIsIAogICAgY2VydGlmaWNhdGVJZDogImZhczAwNCIgCiAgfQ==";