// This file contains the student data in an encoded format (Base64).
// This makes it harder for users to view or modify the data directly.
// To update this data, you must re-encode your original data.js file.
// See the README.md for instructions.

const encodedStudentData = "Ly8gVGhpcyBmaWxlIGNvbnRhaW5zIHRoZSBzdHVkZW50IGRhdGEgZm9yIGNlcnRpZmljYXRlIHZlcmlmaWNhdGlvbi4KLy8gVG8gYWRkIGEgbmV3IHN0dWRlbnQsIGNvcHkgb25lIG9mIHRoZSBsaW5lcyBiZWxvdywgcGFzdGUgaXQgYXQgdGhlIGVuZCwKLy8gYW5kIGNoYW5nZSB0aGUgZGV0YWlscy4gTWFrZSBzdXJlIGVhY2ggbGluZSBlbmRzIHdpdGggYSBjb21tYS4KCmNvbnN0IHN0dWRlbnREYXRhID0gWwogIHsgCiAgICByZWdOdW1iZXI6ICJBU1AvMjAyLzAwMSIsIAogICAgbmFtZTogIkEuQi5TLldpdGhhbmFnZSIsIAogICAgY2VydGlmaWNhdGVJZDogImZhczAwMSIgCiAgfSwKICB7IAogICAgcmVnTnVtYmVyOiAiQVNQLzIwMi8wMDIiLCAKICAgIG5hbWU6ICJBLkcuTmFtYWwiLCAKICAgIGNlcnRpZmljYXRlSWQ6ICJmYXMwMDIiIAogIH0sCiAgeyAKICAgIHJlZ051bWJlcjogIkFTUC8yMDIvMDAzIiwgCiAgICBuYW1lOiAiQS5CLlMuV2l0aGFuYWdlIiwgCiAgICBjZXJ0aWZpY2F0ZUlkOiAiZmFzMDAzIiAKICB9LAogIC8vIEFkZCBuZXcgc3R1ZGVudCByZWNvcmRzIGhlcmUKXTsK";
